version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./sanjeevani-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SOCKET_URL=http://localhost:8000
      - REACT_APP_ENABLE_VOICE_COMMANDS=true
      - REACT_APP_ENABLE_3D_MODELS=true
      - REACT_APP_ENABLE_EMERGENCY=true
      - REACT_APP_MAX_3D_QUALITY=high
    networks:
      - sanjeevani-network

  # Backend service
  backend:
    build:
      context: ./sanjeevani-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - PORT=8000
      - DEBUG=false
      - CORS_ORIGINS=http://localhost:3000
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=sanjeevani
      - JWT_SECRET_KEY=your-secret-key-for-development
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
      - LOG_LEVEL=info
      - ENVIRONMENT=development
    networks:
      - sanjeevani-network

  # MongoDB service
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - sanjeevani-network

networks:
  sanjeevani-network:
    driver: bridge

volumes:
  mongodb-data:
