services:
  # API Service
  - type: web
    name: sanjeevani-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://sanjeevani-health.com,https://www.sanjeevani-health.com
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: Sanjeevani Health
      - key: LOG_LEVEL
        value: info
      - key: SENTRY_DSN
        sync: false
      - key: ENVIRONMENT
        value: production
