name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'sanjeevani-backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'sanjeevani-backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sanjeevani-backend

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: './sanjeevani-backend/requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "PORT=8000" > .env
        echo "DEBUG=true" >> .env
        echo "USE_MOCK_DATA=true" >> .env
        echo "JWT_SECRET_KEY=test_secret_key" >> .env
        echo "JWT_ALGORITHM=HS256" >> .env
        echo "JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60" >> .env
        echo "CORS_ORIGINS=http://localhost:3000" >> .env
    
    - name: Run tests
      run: |
        pytest -v
